// <auto-generated />
namespace SmartStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addeduserpoint2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeduserpoint2));
        
        string IMigrationMetadata.Id
        {
            get { return "202012081133082_added-user-point2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
