// <auto-generated />
namespace SmartStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fixedproductgroupparentrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixedproductgroupparentrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "202012051004189_fixed-product-group-parent-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
