// <auto-generated />
namespace SmartStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Updatedproduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Updatedproduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202012060618192_Updated-product"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
